### ISSUE TITLE
hello sir

### ISSUE THREAD

**Issue by vinodkinoni** [rohailtaha/Automated-Attendance-Project-Using-Face-Recognition#2]
can u plz tell what the version of liabrary

**Comment by rohailtaha** [comment]
Yes of course,
- **face-recognition**  version 1.3.0  
- **cmake**  version 3.22.1
- **dlib**  version 19.22.1
- **opencv-python** version  4.5.3.56
- **numpy**  version 1.21.2
I have updated my README.md to include versions.

**Comment by vinodkinoni** [comment]
thanks sir
